
- include: git.yml

- include: gnupg.yml

- name: Create ~/projects/private Directory
  file:
    state: directory
    path: ~/projects/private

- name: Pull Private Repositories
  git:
    repo: "git@github.com:{{ item }}.git"
    dest: "~/projects/private/{{ item }}"
    update: no
  loop: "{{ github_projects }}"
