- name: Ensuring Homebrew Is Installed
  shell: command -v brew >/dev/null 2>&1
  ignore_errors: yes
  register: "homebrew_installed"

- name: Installing Homebrew
  command: '/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
  when: not homebrew_installed