- import_tasks: sdkman-config.yml

- import_tasks: fzf.yml

- import_tasks: mtr.yml

- import_tasks: youtube-dl.yml

- import_tasks: vim.yml

- import_tasks: zsh.yml

- import_tasks: cheat.yml

- name: Enforce OSX-specific Key Bindings
  lineinfile:
    dest: ~/.zshrc
    regexp: "{{ item.value }}"
    line: "bindkey \"{{ item.key }}\" {{ item.value }}"
    state: present
  with_items:
    - { key: '^[a', value: 'beginning-of-line' }
    - { key: '^[e', value: 'end-of-line' }
    - { key: '\e[A', value: 'history-search-backward' }
    - { key: '\e[B', value: 'history-search-forward' }


- name: Verify if iTerm Runs at Login
  command: osascript -e 'tell application "System Events" to get the name of every login item'
  register: login_items
  changed_when: false
  ignore_errors: true

- name: Run iTerm At Login
  command: osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/iTerm.app", hidden:true}'
  when: "'iTerm' not in login_items.stdout"
  ignore_errors: true
  become: true

- name: hide iTerm from Dock
  osx_defaults: domain=com.googlecode.iterm2 key=HideFromDockAndAppSwitcher type=bool value=true
  tags:
    - iterm
  notify:
    - Kill iTerm
    - Start iTerm

- name: Create ~/Library/Application Support/iTerm2/DynamicProfiles Directory
  file:
    state: directory
    path: "~/Library/Application Support/iTerm2/DynamicProfiles"
  tags: dotfiles

- name: Set iterm2 profile
  file:
    src: "~/dotfiles/iterm2/Profiles.json"
    dest: "~/Library/Application Support/iTerm2/DynamicProfiles/Profiles.json"
    state: link
  tags: dotfiles

- name: Use Touch ID for sudo
  tags: sudo
  shell: sed "s/^#auth/auth/" /etc/pam.d/sudo_local.template | sudo tee /etc/pam.d/sudo_local
  become: true

