---
- name: Install mtr
  homebrew:
    name: mtr
    state: present
  tags:
    - brew
    - mtr
    - terminal

- name: Setup mtr permissions
  shell: 'chown root $(which mtr-packet) && chmod 4755 $(which mtr-packet)'
  become: yes
  tags:
    - mtr
    - terminal