- name: Updating Homebrew
  homebrew:
    update_homebrew: true
  tags:
    - brew
    - basic-tools

- name: Installing Homebrew Packages
  homebrew:
    name:
      - aws-shell
      - awscli
      - bash
      - bash-completion
      - bat
      - bottom
      - curl
      - curlie
      - direnv
      - docker
      - docker-compose
      - duf
      - exa
      - gnutls
      - htop
      - httpie
      - jenv
      - jq
      - lsd
      - maven
      - mc
      - neofetch
      - nmap
      - ncdu
      - pstree
      - python
      - rust
      - tree
      - wget
      - yt-dlp
      - yadm
      - watch
      - gnu-sed
      - coreutils
    state: present
  tags:
    - brew
    - basic-tools

- name: Installing Homebrew Cask Packages
  homebrew_cask:
    name:
      - apptivate
      - cyberduck
      - caffeine
      - docker
      - google-chrome
      - iterm2
      - kitty
      - karabiner-elements
      - slack
      - vlc
      - wireshark
    state: present
    accept_external_apps: yes
  tags:
    - brew
    - cask
    - basic-tools
