- name: Link dotfiles directory
  file:
    src: "~/Dropbox/conf"
    dest: "~/dotfiles"
    state: link

- name: Link dotfiles
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - { src: '~/.SpaceVim', dest: '~/.vim' }
  tags: dotfiles
